# Generated by Django 4.0.2 on 2022-03-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
